# escalation_tool.py

# Import the exact function created by your teammate
from authority_lookup import get_authorities

def get_escalation_mapping(state: str, district: str, issue: str, severity_level: str, days_unresolved: int = 0) -> dict:
    """
    Determines the escalation level based on initial string severity ("LOW", "MEDIUM", "HIGH", "CRITICAL")
    and days unresolved, then fetches the appropriate authority details.
    """
    
    # Normalize input
    severity_level = severity_level.strip().upper()

    # 1. Determine Base Level from the String Severity
    # Matches the output generated by severity_agent.py
    if severity_level == "CRITICAL":
        base_level = 3
    elif severity_level == "HIGH":
        base_level = 2
    else:
        # LOW and MEDIUM both start at Level 1
        base_level = 1

    # 2. Apply Time-Based Escalation (Aging)
    # Bumps the complaint up 1 level for every 7 days it goes unresolved
    time_bump = days_unresolved // 7 
    final_level = min(base_level + time_bump, 4) # Cap at level 4 (CPGRAMS)

    # 3. Fetch all Authorities for the given region and issue
    # Calling the O(1) dictionary lookup built by your teammate
    authorities = get_authorities(state, district, issue)
    
    # Handle the error format defined in authority_lookup.py
    if "error" in authorities:
        return {"error": authorities["error"]}

    # 4. Extract Primary Contact for the calculated level
    primary_contact = authorities.get(f"level{final_level}", {})

    # 5. Determine who to CC
    cc_contact = {}
    
    # If it's a MEDIUM/HIGH/CRITICAL issue and hasn't reached the top level yet, CC the boss
    if final_level < 4 and severity_level in ["MEDIUM", "HIGH", "CRITICAL"]: 
        cc_contact = authorities.get(f"level{final_level + 1}", {})

    return {
        "current_escalation_level": final_level,
        "primary_contact": primary_contact,
        "cc_contact": cc_contact,
        "reasoning": f"Initial severity: {severity_level}. Unresolved for {days_unresolved} days."
    }

# --- Example Usage for Testing ---
if __name__ == "__main__":
    # Test 1: Simulating an output from severity_agent.py ("MEDIUM") that has been ignored for 10 days
    # Base Level = 1. Time Bump = 1 (10 // 7). Final Level = 2.
    result = get_escalation_mapping(
        state="Punjab", 
        district="Amritsar", 
        issue="Air Pollution", 
        severity_level="MEDIUM", 
        days_unresolved=10
    )
    
    import json
    print("Escalation Result:")
    print(json.dumps(result, indent=2))